root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["waiting for changes"]
  bin = "/bin/echo"
  cmd = "go test ./..."
  delay = 1000
  exclude_dir = ["frontend", "assets", "tmp", "vendor", "testdata", "docs", "model/database/query"]
  exclude_file = []
  exclude_regex = ["_mock"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = [".env"]
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  pre_cmd = ["go generate"]
  post_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
