version: '3.7'

services:
  backend:
    image: cosmtrek/air
    working_dir: /backend
    ports:
      - 3000:3000
    volumes:
      - ./:/backend/

  frontend:
    command: yarn dev
    build:
      context: frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"

