version: '3.7'

services:
  app:
    build:
        context: .
    env_file: .env
    ports:
      - "3000:3000"

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "54321:5432"

  mail:
    image: axllent/mailpit
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - .docker/mail:/secrets
    environment:
      MP_MAX_MESSAGES: 500
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_TLS_CERT: /secrets/cert.pem
      MP_SMTP_TLS_KEY: /secrets/privkey.pem

