version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app

  frontend:
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      docker: True
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  mail:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - .docker/mail:/secrets
    environment:
      MP_MAX_MESSAGES: 500
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
      MP_SMTP_TLS_CERT: /secrets/cert.pem
      MP_SMTP_TLS_KEY: /secrets/privkey.pem
