/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ApiProjectCloneUrlResponse
 */
export interface ApiProjectCloneUrlResponse {

    /**
     * @type {string}
     * @memberof ApiProjectCloneUrlResponse
     */
    httpUrlToRepo: string;

    /**
     * @type {string}
     * @memberof ApiProjectCloneUrlResponse
     */
    projectId: string;

    /**
     * @type {string}
     * @memberof ApiProjectCloneUrlResponse
     */
    sshUrlToRepo: string;
}
