/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface ClassroomRunnerResponse
 */
export interface ClassroomRunnerResponse {

    /**
     * @type {boolean}
     * @memberof ClassroomRunnerResponse
     */
    active: boolean;

    /**
     * @type {string}
     * @memberof ClassroomRunnerResponse
     */
    description: string;

    /**
     * @type {number}
     * @memberof ClassroomRunnerResponse
     */
    id: number;

    /**
     * @type {string}
     * @memberof ClassroomRunnerResponse
     */
    ipAddress: string;

    /**
     * @type {boolean}
     * @memberof ClassroomRunnerResponse
     */
    isShared: boolean;

    /**
     * @type {string}
     * @memberof ClassroomRunnerResponse
     */
    name: string;

    /**
     * @type {boolean}
     * @memberof ClassroomRunnerResponse
     */
    online: boolean;

    /**
     * @type {boolean}
     * @memberof ClassroomRunnerResponse
     */
    paused: boolean;

    /**
     * @type {string}
     * @memberof ClassroomRunnerResponse
     */
    runnerType: string;

    /**
     * @type {string}
     * @memberof ClassroomRunnerResponse
     */
    status: string;

    /**
     * @type {string}
     * @memberof ClassroomRunnerResponse
     */
    token: string;

    /**
     * @type {string}
     * @memberof ClassroomRunnerResponse
     */
    tokenExpiresAt: string;
}
