/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { UserClassroomResponse } from './user-classroom-response';
 /**
 * 
 *
 * @export
 * @interface TeamResponse
 */
export interface TeamResponse {

    /**
     * @type {string}
     * @memberof TeamResponse
     */
    createdAt: string;

    /**
     * @type {number}
     * @memberof TeamResponse
     */
    groupId: number;

    /**
     * @type {string}
     * @memberof TeamResponse
     */
    id: string;

    /**
     * @type {Array<UserClassroomResponse>}
     * @memberof TeamResponse
     */
    members: Array<UserClassroomResponse>;

    /**
     * @type {string}
     * @memberof TeamResponse
     */
    name: string;

    /**
     * @type {string}
     * @memberof TeamResponse
     */
    updatedAt: string;

    /**
     * @type {string}
     * @memberof TeamResponse
     */
    webUrl: string;
}
