/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AssignmentTestRequest } from './assignment-test-request';
 /**
 * 
 *
 * @export
 * @interface UpdateAssignmentTestRequest
 */
export interface UpdateAssignmentTestRequest {

    /**
     * @type {Array<AssignmentTestRequest>}
     * @memberof UpdateAssignmentTestRequest
     */
    assignmentTests: Array<AssignmentTestRequest>;

    /**
     * @type {boolean}
     * @memberof UpdateAssignmentTestRequest
     */
    junitAutoGradingActive: boolean;
}
