/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GradingManualResultRequest } from './grading-manual-result-request';
 /**
 * 
 *
 * @export
 * @interface UpdateAssignmentGradingRequest
 */
export interface UpdateAssignmentGradingRequest {

    /**
     * @type {Array<GradingManualResultRequest>}
     * @memberof UpdateAssignmentGradingRequest
     */
    gradingManualRubrics: Array<GradingManualResultRequest>;
}
