/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {string}
     * @memberof User
     */
    avatarURL: string;

    /**
     * @type {string}
     * @memberof User
     */
    fallbackAvatarURL: string;

    /**
     * @type {string}
     * @memberof User
     */
    gitlabEmail: string;

    /**
     * @type {string}
     * @memberof User
     */
    gitlabUsername: string;

    /**
     * @type {number}
     * @memberof User
     */
    id: number;

    /**
     * @type {string}
     * @memberof User
     */
    name: string;
}
