/* tslint:disable */
/* eslint-disable */
/**
 * GitClassrooms – Backend API
 * This is the API for our GitClassrooms Webapp.
 *
 * OpenAPI spec version: develop
 * Contact: info@git-classrooms.dev
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/assignment-api';
export * from './apis/auth-api';
export * from './apis/classroom-api';
export * from './apis/grading-api';
export * from './apis/info-api';
export * from './apis/member-api';
export * from './apis/project-api';
export * from './apis/report-api';
export * from './apis/runners-api';
export * from './apis/team-api';

