name: Build and push to package registry (Develop)
on:
  workflow_dispatch:
  push:
    paths:
      - "code_gen/**"
      - "config/**"
      - "controller/**"
      - "frontend/**"
      - "model/**"
      - "repository/**"
      - "router/**"
      - "utils/**"
      - "worker/**"
      - "wrapper/**"
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "main.go"
    branches:
      - develop

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      COMMIT_SHA: ${{ steps.set_commit_sha.outputs.COMMIT_SHA }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set commit sha
        id: set_commit_sha
        run: |
          COMMIT_SHA=$(git rev-parse --short $GITHUB_SHA)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: "${{ github.repository }}"

      - name: get build time
        run: |
          echo "BUILD_TIME=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >>${GITHUB_ENV}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            APP_VERSION=development
            APP_GIT_COMMIT=${{env.COMMIT_SHA}}
            APP_GIT_BRANCH=develop
            APP_BUILD_TIME=${{env.BUILD_TIME}}
            APP_GIT_REPOSITORY=${{github.repository}}
          file: ./Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}:dev
